sudo: required
services:
  - docker

before_install:
  - docker build -t assaf007/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true assaf007/react-test npm test -- --colors --coverage --watchAll=false

after_success:
  - docker build -t assaf007/multi-client ./client
  - docker build -t assaf007/multi-nginx ./nginx
  - docker build -t assaf007/multi-server ./server
  - docker build -t assaf007/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push assaf007/multi-client
  - docker push assaf007/multi-nginx
  - docker push assaf007/multi-server
  - docker push assaf007/multi-worker
